In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
sent=['the glass of milk',
      'the glassnof juice',
      'iam a good boy',
      'iam a good developer',
      'understand the meaning of words',
      'your videos are good']

In [7]:
sent

['the glass of milk',
 'the glassnof juice',
 'iam a good boy',
 'iam a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
#define the vocab size
voc_size=10000

In [11]:
#one hot representation
one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep

[[2296, 3497, 6874, 5513],
 [2296, 329, 4303],
 [2910, 5744, 4684, 6436],
 [2910, 5744, 4684, 5169],
 [7990, 2296, 9290, 6874, 3327],
 [6504, 7878, 1139, 4684]]

In [12]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [13]:
import numpy as np

In [15]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2296 3497 6874 5513]
 [   0    0    0    0    0 2296  329 4303]
 [   0    0    0    0 2910 5744 4684 6436]
 [   0    0    0    0 2910 5744 4684 5169]
 [   0    0    0 7990 2296 9290 6874 3327]
 [   0    0    0    0 6504 7878 1139 4684]]


In [23]:
#feature representation
sent_length=8
dim=10

In [24]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [22]:
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step


array([[[ 0.01588497,  0.00114193, -0.01671376,  0.03922987,
         -0.04837659,  0.01856497, -0.03330084,  0.00143542,
         -0.03505145, -0.02742325],
        [ 0.01588497,  0.00114193, -0.01671376,  0.03922987,
         -0.04837659,  0.01856497, -0.03330084,  0.00143542,
         -0.03505145, -0.02742325],
        [ 0.01588497,  0.00114193, -0.01671376,  0.03922987,
         -0.04837659,  0.01856497, -0.03330084,  0.00143542,
         -0.03505145, -0.02742325],
        [ 0.01588497,  0.00114193, -0.01671376,  0.03922987,
         -0.04837659,  0.01856497, -0.03330084,  0.00143542,
         -0.03505145, -0.02742325],
        [-0.03039128, -0.02750882,  0.01059116,  0.03036335,
          0.04154241,  0.02815701, -0.03510089, -0.03275754,
          0.00285558,  0.00741017],
        [-0.04023635, -0.01121875, -0.01148534, -0.04828469,
         -0.04484134,  0.02579222, -0.02649835, -0.02425842,
         -0.01761959,  0.00325129],
        [ 0.04207906,  0.04124289,  0.01923177, -0.0

In [1]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

# Example data
sent = [
    'the glass of milk',
    'the glass of juice',
    'iam a good boy',
    'iam a good developer',
    'understand the meaning of words',
    'your videos are good'
]

# 1) Set vocabulary size
voc_size = 10000

# 2) One-hot encode sentences
one_hot_rep = [one_hot(words, voc_size) for words in sent]

# 3) Set fixed sentence length BEFORE creating model
sent_length = 8

# 4) Pad sequences
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print("Padded Sequences:\n", embedded_docs)

# 5) Set embedding dimension BEFORE creating model
dim = 10

# 6) CREATE MODEL NOW (after variables exist)
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

# 7) Check model
model.summary()


Padded Sequences:
 [[   0    0    0    0 5917 2348 3302 3693]
 [   0    0    0    0 5917 2348 3302 3123]
 [   0    0    0    0 9942 1275 1750 9065]
 [   0    0    0    0 9942 1275 1750 9813]
 [   0    0    0  704 5917 3567 3302 9280]
 [   0    0    0    0  937 6307 2051 1750]]


d:\Udemy\project1\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [2]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

sent = [
    'the glass of milk',
    'the glass of juice',
    'iam a good boy',
    'iam a good developer',
    'understand the meaning of words',
    'your videos are good'
]

voc_size = 10000
one_hot_rep = [one_hot(words, voc_size) for words in sent]

sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

dim = 10

model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

# build model before summary
model.build(input_shape=(None, sent_length))
model.summary()


[[   0    0    0    0 5917 2348 3302 3693]
 [   0    0    0    0 5917 2348 3302 3123]
 [   0    0    0    0 9942 1275 1750 9065]
 [   0    0    0    0 9942 1275 1750 9813]
 [   0    0    0  704 5917 3567 3302 9280]
 [   0    0    0    0  937 6307 2051 1750]]


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [3]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step


array([[[-0.02148332,  0.01015419,  0.03351437,  0.00398906,
         -0.04597278,  0.00803901,  0.02296208, -0.01423353,
         -0.04303366,  0.0299011 ],
        [-0.02148332,  0.01015419,  0.03351437,  0.00398906,
         -0.04597278,  0.00803901,  0.02296208, -0.01423353,
         -0.04303366,  0.0299011 ],
        [-0.02148332,  0.01015419,  0.03351437,  0.00398906,
         -0.04597278,  0.00803901,  0.02296208, -0.01423353,
         -0.04303366,  0.0299011 ],
        [-0.02148332,  0.01015419,  0.03351437,  0.00398906,
         -0.04597278,  0.00803901,  0.02296208, -0.01423353,
         -0.04303366,  0.0299011 ],
        [ 0.04446632,  0.01923782, -0.04979537, -0.01723624,
         -0.03507886, -0.03851686, -0.00868843,  0.04810822,
          0.03693462, -0.00665702],
        [ 0.0033191 ,  0.03340021,  0.04149114, -0.01736853,
          0.03086586, -0.02385668, -0.03828449, -0.00049523,
          0.02369278, -0.00736487],
        [ 0.03945744,  0.02033107,  0.04609256,  0.0